### ISSUE TITLE
Notice: Undefined variable: safety in C:\xampp\htdocs\DWM2R\index.php on line 530

### ISSUE THREAD

**Issue by Linkzard** [TheCowness/DWM2Randomizer#1]
Notice: Undefined variable: safety in C:\xampp\htdocs\DWM2R\index.php on line 530

getting that error a dozen times before it goes over to symbol spam when I try to randomize my rom

**Comment by TheCowness** [comment]
I fixed this a couple months ago, but forgot to commit and close this ticket.  I had to roll back the live version today, but I rolled it past the revision that introduced this bug, so either way this can be closed.
