### ISSUE TITLE
Website down - any other way to grab the randomizer?

### ISSUE THREAD

**Issue by Linkzard** [TheCowness/DWM2Randomizer#3]
Had to format my PC and lost the files I previously had randomized. 

With the website seemingly being down, is there any other way to get the randomizer? Downloading the repo didn't yield any satisfying results since I didn't see anything exectuable in it.

**Comment by TheCowness** [comment]
Unfortunately, you'd have to install PHP and basically set up a web server to run the randomizer locally.  I usually host it off a PC in my house, but I moved over the weekend and am not quite set up yet.  I'm waiting on two USB wireless network adapters that Amazon said would be here last night, but if they show up today I'll get it set back up tonight.

Sorry for the inconvenience!

**Comment by Linkzard** [comment]
No problem! I will see if I can get the hosting done myself, otherwise I will just wait until you are properly settled in since I'm in no rush.

I hope the move went smoothly tho.

**Comment by TheCowness** [comment]
All right well it turns out I don't have a static IP with this ISP by default, and they're saying it could be up to two weeks until I get one, so that's the current holdup.  I give it 50% odds that it's working tomorrow, and 50% odds it takes the entire two weeks, but we'll see.

**Comment by TheCowness** [comment]
Forgot about this ticket, but this was resolved like two and a half months ago.  Closing issue.
